// Automatically generated by syz-sysgen; DO NOT EDIT.

package sys

import (
	"embed"

	"github.com/google/syzkaller/sys/generated"

	"github.com/google/syzkaller/sys/darwin"
	"github.com/google/syzkaller/sys/freebsd"
	"github.com/google/syzkaller/sys/fuchsia"
	"github.com/google/syzkaller/sys/linux"
	"github.com/google/syzkaller/sys/netbsd"
	"github.com/google/syzkaller/sys/openbsd"
	"github.com/google/syzkaller/sys/test"
	"github.com/google/syzkaller/sys/trusty"
	"github.com/google/syzkaller/sys/windows"
)

//go:embed gen/*.gob.flate
var files embed.FS

func init() {
	generated.Register("darwin", "amd64", "872bba2ae5409477b673378e8bd7f3c4cb76fb57", darwin.InitTarget, files)
	generated.Register("freebsd", "386", "998df1771bdbed95c1e813657f0303c22863bda9", freebsd.InitTarget, files)
	generated.Register("freebsd", "amd64", "7a1a79c48c6b0d28f10f90a3d8f605b6a03a18a9", freebsd.InitTarget, files)
	generated.Register("freebsd", "arm64", "7a1a79c48c6b0d28f10f90a3d8f605b6a03a18a9", freebsd.InitTarget, files)
	generated.Register("freebsd", "riscv64", "7a1a79c48c6b0d28f10f90a3d8f605b6a03a18a9", freebsd.InitTarget, files)
	generated.Register("fuchsia", "amd64", "964c7fd4b1c8b2f056ea0047c6f157b808eace6d", fuchsia.InitTarget, files)
	generated.Register("fuchsia", "arm64", "aabea56d7a220b467494a72b09e415bcfe2e82a0", fuchsia.InitTarget, files)
	generated.Register("linux", "386", "09de373212bf3550d1e7438552044f41bed04cbf", linux.InitTarget, files)
	generated.Register("linux", "amd64", "7fe4d94b74e5352d89f38fb250e8f1be8987363e", linux.InitTarget, files)
	generated.Register("linux", "arm", "8e0845864998e8ad760187435dcd3c2d70af1952", linux.InitTarget, files)
	generated.Register("linux", "arm64", "892b26708eec1518e4267154daea46e6e2267046", linux.InitTarget, files)
	generated.Register("linux", "mips64le", "4655ef0ae8cd86a2c82d31a5ee5a56f89a0a960c", linux.InitTarget, files)
	generated.Register("linux", "ppc64le", "29aebb0bccea3d657fe0f5a80cec9c12bf61de35", linux.InitTarget, files)
	generated.Register("linux", "riscv64", "e68ab3660b8c69f316d948d54210f4172245793c", linux.InitTarget, files)
	generated.Register("linux", "s390x", "07c7d6a64c5083880c2c56048caa2324e6f8e373", linux.InitTarget, files)
	generated.Register("netbsd", "amd64", "e55c41320cbb764d170d09a2ed5dbe024471a081", netbsd.InitTarget, files)
	generated.Register("openbsd", "amd64", "1ea000ab9607526f7e5426a3893355348153b581", openbsd.InitTarget, files)
	generated.Register("test", "32", "774bd1833e3c8b50f116747de65cf245dbbe7492", test.InitTarget, files)
	generated.Register("test", "32_fork", "b11ab04652e27605ae4a1816ebf7989860974245", test.InitTarget, files)
	generated.Register("test", "64", "3f4c92b9a77e3109f812dc47cdb5d09ecbecd741", test.InitTarget, files)
	generated.Register("test", "64_fork", "0282491ed7d87770001881623ce2ff0bd544caff", test.InitTarget, files)
	generated.Register("test", "64_fuzz", "2fdc070f08aa526d39a3f3e403d6624b1ac963bd", test.InitTarget, files)
	generated.Register("trusty", "arm", "e15883cf9bc294d71c2d4e06d02c4bda0414a94f", trusty.InitTarget, files)
	generated.Register("windows", "amd64", "f14e4fef7483fea72b1b0867de524882897680c6", windows.InitTarget, files)

}
